# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to draw event.
#' @param event_prob event probability vector
#' @return event
#' @export
sample_event <- function(event_prob) {
    .Call('_TRAISIERCPP_sample_event', PACKAGE = 'TRAISIERCPP', event_prob)
}

#' CPP function to execute expensive loop
#' @param timeval timeval
#' @param total_time total time
#' @param gam immigration rate
#' @param laa anagenetic rate
#' @param lac cladogenetic rate
#' @param mu extinction rate
#' @param K K
#' @param mainland_n number of species on mainland
#' @param trait_pars_R trait pars
#' @return list with stt_table and island_spec
#' @export
execute_time_loop <- function(timeval, total_time, gam, laa, lac, mu, K, mainland_n, trait_pars_R) {
    .Call('_TRAISIERCPP_execute_time_loop', PACKAGE = 'TRAISIERCPP', timeval, total_time, gam, laa, lac, mu, K, mainland_n, trait_pars_R)
}

#' function to test get_immigration_rate
#' @param gam gam
#' @param A A
#' @param num_spec num species
#' @param K K value
#' @param mainland_n num mainland species trait 1
#' @param mainland_n2 num mainland species trait 2
#' @param immig_rate2 gam2
#' @return two rates
#' @export
test_get_immig_rate <- function(gam, A, num_spec, K, mainland_n, mainland_n2, immig_rate2) {
    .Call('_TRAISIERCPP_test_get_immig_rate', PACKAGE = 'TRAISIERCPP', gam, A, num_spec, K, mainland_n, mainland_n2, immig_rate2)
}

#' function to test get_ext_rate
#' @param mu mu
#' @param num_spec num species
#' @param A A
#' @param ext_rate2 ext_rate2
#' @param num_spec_trait1 num_spec trait 1
#' @param num_spec_trait2 num_spec trait 2
#' @return two rates
#' @export
test_get_ext_rate <- function(mu, num_spec, A, ext_rate2, num_spec_trait1, num_spec_trait2) {
    .Call('_TRAISIERCPP_test_get_ext_rate', PACKAGE = 'TRAISIERCPP', mu, num_spec, A, ext_rate2, num_spec_trait1, num_spec_trait2)
}

#' function to test get_ana_rate
#' @param laa anagenesis rate trait 1
#' @param num_immigrants number of immigrants
#' @param ana_rate2 ana_rate trait 2
#' @param num_spec_trait1 num_spec trait 1
#' @param num_spec_trait2 num_spec trait 2
#' @return two rates
#' @export
test_get_ana_rate <- function(laa, num_immigrants, ana_rate2, num_spec_trait1, num_spec_trait2) {
    .Call('_TRAISIERCPP_test_get_ana_rate', PACKAGE = 'TRAISIERCPP', laa, num_immigrants, ana_rate2, num_spec_trait1, num_spec_trait2)
}

#' function to test_get_clado_rate
#' @param lac clado rate trait 1
#' @param num_spec number of species
#' @param K K
#' @param A A
#' @param clado_rate2 clado rate trait 2
#' @param num_spec_trait1 num_spec trait 1
#' @param num_spec_trait2 num_spec trait 2
#' @return two rates
#' @export
test_get_clado_rate <- function(lac, num_spec, K, A, clado_rate2, num_spec_trait1, num_spec_trait2) {
    .Call('_TRAISIERCPP_test_get_clado_rate', PACKAGE = 'TRAISIERCPP', lac, num_spec, K, A, clado_rate2, num_spec_trait1, num_spec_trait2)
}

#' function to test get_trans_rate
#' @param trans_rate tr1
#' @param trans_rate2 tr2
#' @param num_spec_trait1 num_spec trait 1
#' @param num_spec_trait2 num_spec trait 2
#' @return two rates
#' @export
test_get_trans_rate <- function(trans_rate, trans_rate2, num_spec_trait1, num_spec_trait2) {
    .Call('_TRAISIERCPP_test_get_trans_rate', PACKAGE = 'TRAISIERCPP', trans_rate, trans_rate2, num_spec_trait1, num_spec_trait2)
}

#' function to test get_trans_rate
#' @param timeval timeval
#' @param total_time total time
#' @param gam gam
#' @param laa laa
#' @param lac lac
#' @param mu mu
#' @param K K
#' @param num_spec num_spec
#' @param num_immigrants num_immigrants
#' @param mainland_n mainland_n
#' @param island_spec island_spec
#' @param trait_pars trait pars
#' @return two rates
#' @export
test_update_rates <- function(timeval, total_time, gam, laa, lac, mu, K, num_spec, num_immigrants, mainland_n, island_spec_R, trait_pars_R) {
    .Call('_TRAISIERCPP_test_update_rates', PACKAGE = 'TRAISIERCPP', timeval, total_time, gam, laa, lac, mu, K, num_spec, num_immigrants, mainland_n, island_spec_R, trait_pars_R)
}

#' test draw prop
#' @param Rcpp::NumericVector probs
#' @return drawn index
#' @export
test_draw_prop <- function(v) {
    .Call('_TRAISIERCPP_test_draw_prop', PACKAGE = 'TRAISIERCPP', v)
}

#' test immigration
#' @param timeval timeval
#' @param mainland_spec vector
#' @param island_spec_R matrix
#' @return stringmatrix island_spec
#' @export
test_immigration <- function(timeval, mainland_spec_R, island_spec_R) {
    .Call('_TRAISIERCPP_test_immigration', PACKAGE = 'TRAISIERCPP', timeval, mainland_spec_R, island_spec_R)
}

#' test extinction
#' @param island_spec_R island spec table
#' @param focal_trait focal trait
#' @return island spec table
#' @export
test_extinction <- function(island_spec_R, focal_trait) {
    .Call('_TRAISIERCPP_test_extinction', PACKAGE = 'TRAISIERCPP', island_spec_R, focal_trait)
}

#' test execute extinction without rng
#' @param island_spec_R island spec table
#' @param index index
#' @return island spec table
#' @export
test_execute_extinction <- function(island_spec_R, index) {
    .Call('_TRAISIERCPP_test_execute_extinction', PACKAGE = 'TRAISIERCPP', island_spec_R, index)
}

#' test execute anagenesis
#' @param island_spec_R island spec table
#' @param maxspecID maxspecid
#' @param focal_trait focaltrait
#' @return island spec table
#' @export
test_anagenesis <- function(island_spec_R, maxspecID, focal_trait) {
    .Call('_TRAISIERCPP_test_anagenesis', PACKAGE = 'TRAISIERCPP', island_spec_R, maxspecID, focal_trait)
}

