# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CPP function to execute expensive loop
#' @param timeval timeval
#' @param total_time total time
#' @param gam immigration rate
#' @param laa anagenetic rate
#' @param lac cladogenetic rate
#' @param mu extinction rate
#' @param area_pars_from_R area pars
#' @param K K
#' @param num_spec number of species
#' @param num_immigrants number of immigrants
#' @param mainland_n number of species on mainland
#' @param maxspecID maxpsecid
#' @param trait_pars_R trait pars
#' @param mainland_spec_R mainland spec
#' @return list with stt_table and island_spec
#' @export
execute_time_loop <- function(timeval, total_time, gam, laa, lac, mu, area_pars_from_R, K, mainland_n, trait_pars_R) {
    .Call('_TRAISIERCPP_execute_time_loop', PACKAGE = 'TRAISIERCPP', timeval, total_time, gam, laa, lac, mu, area_pars_from_R, K, mainland_n, trait_pars_R)
}

