# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to draw event.
#' @param event_prob event probability vector
#' @return event
#' @export
sample_event <- function(event_prob) {
    .Call('_TRAISIERCPP_sample_event', PACKAGE = 'TRAISIERCPP', event_prob)
}

#' function to test get_immigration_rate
#' @param gam gam
#' @param A A
#' @param num_spec num species
#' @param K K value
#' @param mainland_n num mainland species trait 1
#' @param mainland_n2 num mainland species trait 2
#' @param immig_rate2 gam2
#' @return two rates
#' @export
test_get_immig_rate <- function(gam, A, num_spec, K, mainland_n, mainland_n2, immig_rate2) {
    .Call('_TRAISIERCPP_test_get_immig_rate', PACKAGE = 'TRAISIERCPP', gam, A, num_spec, K, mainland_n, mainland_n2, immig_rate2)
}

#' function to test get_ext_rate
#' @param mu mu
#' @param num_spec num species
#' @param A A
#' @param ext_rate2 ext_rate2
#' @param num_spec_trait1 num_spec trait 1
#' @param num_spec_trait2 num_spec trait 2
#' @return two rates
#' @export
test_get_ext_rate <- function(mu, num_spec, A, ext_rate2, num_spec_trait1, num_spec_trait2) {
    .Call('_TRAISIERCPP_test_get_ext_rate', PACKAGE = 'TRAISIERCPP', mu, num_spec, A, ext_rate2, num_spec_trait1, num_spec_trait2)
}

#' CPP function to execute expensive loop
#' @param timeval timeval
#' @param total_time total time
#' @param gam immigration rate
#' @param laa anagenetic rate
#' @param lac cladogenetic rate
#' @param mu extinction rate
#' @param area_pars_from_R area pars
#' @param K K
#' @param mainland_n number of species on mainland
#' @param trait_pars_R trait pars
#' @return list with stt_table and island_spec
#' @export
execute_time_loop <- function(timeval, total_time, gam, laa, lac, mu, area_pars_from_R, K, mainland_n, trait_pars_R) {
    .Call('_TRAISIERCPP_execute_time_loop', PACKAGE = 'TRAISIERCPP', timeval, total_time, gam, laa, lac, mu, area_pars_from_R, K, mainland_n, trait_pars_R)
}

